query ListRepositoryInTopic($first: Int) {
  topic(name: "dotfiles") {
    name
    repositories(first: $first) {
      edges {
        node {
          id
          url
          nameWithOwner
          owner {
            id
            avatarUrl
          }
        }
      }
    }
  }
}
